repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.idea/|.vscode/)
      - id: end-of-file-fixer
        exclude: ^(.idea/|.vscode/)
      - id: check-yaml
        exclude: ^(.idea/|.vscode/)
        args: [--unsafe]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/onqlavelabs/pre-commit-golang
    rev: fb24a639f7c938759fe56eeebbb7713b69d60494
    hooks:
      - id: go-fmt
      - id: go-vet
      # - id: go-unit-tests
      - id: golangci-lint
      - id: go-mod-tidy
        # stages: [post-commit, post-merge, manual]
